### ISSUE TITLE
[bug] 私有群组音频链接无法解析

### ISSUE THREAD

**Issue by xtaodada** [sam01101/tg-voice-chat-bot#7]
### BUG 发生地址

!tg 私有群组音频链接

### 预期是什么？

将音频添加进播放列表

### 实际发生了什么？

❌ 添加失败, 以下为失败原因:

无法解析链接 - 私有群组音频链接

### 额外信息（日志、报错等）

此行判断将直接把私有群组链接返回为解析失败

https://github.com/sam01101/tg-voice-chat-bot/blob/fdd57fd43df5dc33265bee614a956ced16cc386b/utils.py#L160

**Comment by sam01101** [comment]
@xtaodada 请问是否可以提供一些私有群组的链接例子, 谢谢

**Comment by sam01101** [comment]
@xtaodada 请尝试最新 commit
